"""final_schema

Revision ID: bd71de7b5a05
Revises: 
Create Date: 2026-03-24 21:03:49.669425

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd71de7b5a05'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lessons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_name', sa.String(length=255), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('lesson_number', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=1024), nullable=False),
    sa.Column('lesson_type', sa.String(length=255), nullable=True),
    sa.Column('teacher', sa.String(length=1024), nullable=True),
    sa.Column('room', sa.String(length=255), nullable=True),
    sa.Column('parity', sa.String(length=20), nullable=False),
    sa.Column('week_mask', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lessons_group_name'), 'lessons', ['group_name'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tg_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('registered_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_tg_id'), 'users', ['tg_id'], unique=True)
    op.create_table('profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('course', sa.Integer(), nullable=False),
    sa.Column('group_name', sa.String(length=255), nullable=False),
    sa.Column('study_form', sa.Enum('FULL_TIME', 'PART_TIME', name='studyform'), nullable=False),
    sa.Column('edu_level', sa.Enum('BACHELOR', 'SPECIALIST', 'MAGISTER', 'POSTGRADUATE', name='edulevel'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profiles_group_name'), 'profiles', ['group_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_profiles_group_name'), table_name='profiles')
    op.drop_table('profiles')
    op.drop_index(op.f('ix_users_tg_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_lessons_group_name'), table_name='lessons')
    op.drop_table('lessons')
    # ### end Alembic commands ###
